version: '3.7'
services:
        db:
                image: postgres:11.4-alpine
                env_file:
                        - .env
                volumes: 
                        - ./tmp/postgres:/var/lib/postgresql/data
                ports:
                        - $DB_HOST:$DB_PORT:5432
                environment:
                        - POSTGRES_PASSWORD=$DB_PASS
                        - POSTGRES_USER=$DB_USER
                        - POSTGRES_DB=$DB_NAME
